name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  test-on-arm64:
    runs-on: ubuntu-latest
    steps:
      - 
        name: install build essentials
        run: 
          sudo apt update && 
          sudo apt install gcc g++ libgtest-dev cmake make build-essential sed gcc-aarch64-linux-gnu g++-aarch64-linux-gnu  
      
      - 
        name: install qemu
        run: 
          sudo apt install qemu-user
        
      - name: cross-compile gtest for arm64
        run: |
          git clone https://github.com/google/googletest.git && 
          mkdir gtest-build && 
          cd gtest-build && cmake ../googletest/ -DCMAKE_INSTALL_PREFIX=/usr/aarch64-linux-gnu -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ && 
          make && sudo make install
      -
        uses: actions/checkout@v3
      -
        name: cmake make and run
        run: |
          mkdir build && cd build && cmake .. && make && ./arm64asm_test
