name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  setup_qemu:
    runs-on: ubuntu-latest
    steps:
      - 
        name: install qemu
        run: |
          sudo apt update && sudo apt install qemu
